### ISSUE TITLE
Contact Details

### ISSUE THREAD

**Issue by shah-smit** [shah-smit/jb-bio-medical#2]
- Do you want to put email? 
- Contact Us Form? - This might need a server...

**Comment by PalakShah93** [comment]
Yes we need to put an email. 

Looks like you already managed to get the server. Dont pay for anything

**Comment by shah-smit** [comment]
This issue can be closed if below form is okay:

https://shah-smit.github.io/jb-bio-medical/?#/contact

The email server is up and ready - currently you can only send email every 3 mins - just to block too many requests.

**Comment by PalakShah93** [comment]
Ya looks good. Add Country text field as optional. Then can close this issue
