### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by PalakShah93** [shah-smit/jb-bio-medical#6]
**1. Company Name & Compnay Logo** 
J B Biomed.
![image](https://user-images.githubusercontent.com/8535769/82354348-4ffe8c80-9a1e-11ea-9566-f7d1eabb153f.png)

**2. Company Address**
A-117, Tirthraj Complex, Opp. V S Hospital,
Ellisbridge, Ahmedabad-380006

**3. Contact Number**
+91 9825065681   

 **4. whats app Number  (Link to whats app directly)**
 +91 9825065681     
If open in mobile - open in whats app
If open in web - open in web whats app if possible. 
// If its taking more time to develop just add whats app icon

**5.Email Address**
 jbbiomed@gmail.com [Incoming and outgoing]

**6. Mission and Vision**
Our Mission and vision are to provide high-tech/ minimal invasive surgical and medical equipment at a very economical price. Also will provide the necessary service to maintain the equipment. 

Our contribution to give continuous support and provide academic help to explore more and more advance surgical operative procedures with high-tech equipments at reasonable charges.

**7 About us** 
J B Biomed is a leading brand in dealing with High tech medical and Endoscopy equipemnts/ instruments, Surgical Lasers in all the major discipline.

**8. In which country you supply products;**
Gujarat, India

**9. Social Media**
Facebook - https://www.facebook.com/mihir.shah.5439

You can do a design like this or you can modify as per limitation of the bootstrap
https://advinhealthcare.com/contact-us/

**Comment by shah-smit** [comment]
@PalakShah93  Updated contact us and about us page

Adding map similiar to advin, it requires google map api key - and for that i have to setup billing acc. so adding might not be good idea unless going live is confirmed

**Comment by PalakShah93** [comment]
Hi @shah-smit , 

Do not set up for google maps API billing. Just add a google map screenshot as below. 
![image](https://user-images.githubusercontent.com/8535769/82330728-d4daad80-9a00-11ea-9f5f-6a9f49f86ef7.png)

About Us looks good. 
Possible to improve the UI for this page? Add icons for contact us , email etc You can choose free one from flat icon or anywhere.

**Comment by PalakShah93** [comment]
Hi @shah-smit , 
I have added the company logi in my first comment. Have a look

**Comment by shah-smit** [comment]
Added logo to about us page - just published.
