### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by PalakShah93** [shah-smit/jb-bio-medical#9]
![image](https://user-images.githubusercontent.com/8535769/82578080-8b799200-9ba9-11ea-8861-11fa5213e20f.png)

PFA for your reference 
Actual Result -  how it looks like when I make the screen smaller. 
Expected Result - It should look good in most of the sizes

**Comment by shah-smit** [comment]
![photo_2020-05-22_00-05-23](https://user-images.githubusercontent.com/13942171/82579157-fafa7c00-9bbf-11ea-8ca9-be68da7f3ab7.jpg)
![photo_2020-05-22_00-05-25](https://user-images.githubusercontent.com/13942171/82579171-fe8e0300-9bbf-11ea-8462-8e6fcd0475ba.jpg)

Here is it, check from phone for better bootstrap!

**Comment by PalakShah93** [comment]
alright, looks good in phone
